Update build-openwrt.yml

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -1,14 +1,13 @@
-name: OpenWrt Builder
+name: openwrt
 
 on:
   workflow_dispatch:
 
 env:
   REPO_URL: https://github.com/openwrt/openwrt.git
-  REPO_BRANCH: v24.10.4
+  REPO_BRANCH: openwrt-24.10
   CONFIG_FILE: .config
-  DIY_P1_SH: op1.sh
-  DIY_P2_SH: op2.sh
+  DIY_SH: diy.sh
   UPLOAD_FIRMWARE: true
   UPLOAD_RELEASE: true
   TZ: Asia/Shanghai
@@ -16,7 +15,7 @@ env:
 jobs:
   build:
     runs-on: ubuntu-22.04
-
+    
     steps:
     - name: 释放磁盘空间
       uses: jlumbroso/free-disk-space@main
@@ -36,14 +35,17 @@ jobs:
       env:
         DEBIAN_FRONTEND: noninteractive
       run: |
-        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
-        sudo docker image prune --all --force
-        sudo sed -i 's/azure\.//' /etc/apt/sources.list
-        sudo -E apt-get -qq update
-        sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
-        sudo -E apt-get -qq autoremove --purge
-        sudo -E apt-get -qq clean
-        sudo timedatectl set-timezone "$TZ"
+        sudo apt-get update -y
+        sudo apt-get install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
+                                bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext \
+                                genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev \
+                                libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev \
+                                libreadline-dev libssl-dev libtool llvm lrzsz libnsl-dev ninja-build p7zip p7zip-full patch pkgconf \
+                                python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion \
+                                swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
+        sudo apt-get autoremove --purge
+        sudo apt-get clean
+        sudo timedatectl set-timezone 'Asia/Shanghai'
         sudo mkdir -p /workdir
         sudo chown $USER:$GROUPS /workdir
 
@@ -57,19 +59,26 @@ jobs:
     - name: Update feeds
       run: cd openwrt && ./scripts/feeds update -a
 
+    - name: Remove some feeds
+      run: |
+        chmod +x $DIY_P3_SH
+        cd openwrt
+        $GITHUB_WORKSPACE/$DIY_P3_SH
+
+    - name: update feed
+      run: cd openwrt && ./scripts/feeds update -a
+
     - name: Install feeds
       run: cd openwrt && ./scripts/feeds install -a
 
-    - name: 添加玩客云设备
+    - name: Load custom configuration
       run: |
+        [ -e patches ] && mv patches openwrt/patches
+        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
+        [ -e gen_aml_emmc_img.sh ] && mv gen_aml_emmc_img.sh openwrt/gen_aml_emmc_img.sh
+        chmod +x $DIY_SH
         cd openwrt
-        git clone https://github.com/dongjany/amlogic.git target/linux/amlogic
-
-    - name: 添加额外软件包
-      run: |
-        chmod +x $DIY_P1_SH
-        cd openwrt
-        $GITHUB_WORKSPACE/$DIY_P1_SH
+        $GITHUB_WORKSPACE/$DIY_SH
 
     - name: 应用补丁
       run: |
@@ -78,18 +87,40 @@ jobs:
         patch -p1 < patches/BRCMFMAC_SDIO.patch
         patch -p1 < patches/onecloud.patch
 
-    - name: 添加自定义设备配置
+    - name: 修复onecloud 1
+      id: package
       run: |
-        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
-        chmod +x $DIY_P2_SH
         cd openwrt
-        $GITHUB_WORKSPACE/$DIY_P2_SH
+        make defconfig
+        make target/linux/prepare -j$(nproc)
+        KERNEL_CONFIG="build_dir/target-arm_cortex-a5+vfpv4_musl_eabi/linux-amlogic_meson8b/linux-6.6.118/.config"
+        if [ ! -f "$KERNEL_CONFIG" ]; then
+          echo "内核配置文件缺失，手动生成..."
+          mkdir -p $(dirname "$KERNEL_CONFIG")
+          cp .config "$KERNEL_CONFIG"
+        fi
+    
+    - name: 修复onecloud 2
+      id: package
+      run: |
+        cd openwrt
+        make toolchain/install -j$(nproc) V=s
+        export PATH=$PATH:$(pwd)/staging_dir/toolchain-arm_cortex-a5+vfpv4_musl_eabi/bin
+        export STAGING_DIR=$(pwd)/staging_dir
+        if [ -f "staging_dir/toolchain-arm_cortex-a5+vfpv4_musl_eabi/bin/arm-openwrt-linux-muslgnueabi-gcc" ]; then
+          echo "工具链生成成功！"
+          staging_dir/toolchain-arm_cortex-a5+vfpv4_musl_eabi/bin/arm-openwrt-linux-muslgnueabi-gcc --version
+        else
+          echo "工具链生成失败，尝试手动查找"
+          find staging_dir -name "arm-openwrt-linux-muslgnueabi-gcc"
+        fi
 
     - name: Download package
       id: package
       run: |
         cd openwrt
         make defconfig
+        echo -e "$(nproc) thread compile"
         make download -j8
         find dl -size -1024c -exec ls -l {} \;
         find dl -size -1024c -exec rm -f {} \;
@@ -97,9 +128,14 @@ jobs:
     - name: Compile the firmware
       id: compile
       run: |
+        set -e
         cd openwrt
         echo -e "$(nproc) thread compile"
-        make -j$(nproc) || make -j1 || make -j1 V=s
+        echo "status=failed" >> $GITHUB_OUTPUT
+        if ! ( make -j$(nproc) || make -j1 || make -j1 V=s ); then
+            echo "❌ Make failed"
+            exit 1
+        fi
         echo "status=success" >> $GITHUB_OUTPUT
         grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
         [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
@@ -156,3 +192,5 @@ jobs:
       with:
         keep_latest: 3
         delete_tags: true
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
